#!/usr/bin/env python3
"""Emits the tiny ONNX model the ORT probe runs, as a C byte array.

Hand-rolled protobuf, standard library only. The point of the probe is to have
nothing between it and the thing being measured, and that property would be lost
if building it needed `onnx` and `protobuf` installed -- in a container, on an
airgapped box, in two years' time.

The model is one Add node over two 1x4 float tensors. Deliberately not an Identity:
Add exercises a real compute kernel and the allocator, which is what has to survive
RTLD_DEEPBIND, whereas Identity could plausibly short-circuit.

    python3 tools/ortprobe/make_model.py > tools/ortprobe/probe_model.inc

Regenerate only if the model changes. The output is committed, because it is ours
and it is 200 bytes -- unlike model weights, which are neither.
"""

import sys

FLOAT = 1


def varint(n):
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        out.append(b | (0x80 if n else 0))
        if not n:
            return bytes(out)


def tag(field, wire):
    return varint((field << 3) | wire)


def vfield(field, value):
    return tag(field, 0) + varint(value)


def lfield(field, payload):
    if isinstance(payload, str):
        payload = payload.encode()
    return tag(field, 2) + varint(len(payload)) + payload


def tensor_type(elem, dims):
    shape = b"".join(lfield(1, vfield(1, d)) for d in dims)
    inner = vfield(1, elem) + lfield(2, shape)
    return lfield(1, inner)  # TypeProto.tensor_type


def value_info(name, dims):
    return lfield(1, name) + lfield(2, tensor_type(FLOAT, dims))


def build():
    node = (
        lfield(1, "a") + lfield(1, "b")   # inputs
        + lfield(2, "c")                  # output
        + lfield(3, "add")                # name
        + lfield(4, "Add")                # op_type
    )
    graph = (
        lfield(1, node)
        + lfield(2, "whitewater_ort_probe")
        + lfield(11, value_info("a", [1, 4]))
        + lfield(11, value_info("b", [1, 4]))
        + lfield(12, value_info("c", [1, 4]))
    )
    opset = lfield(1, "") + vfield(2, 13)
    return (
        vfield(1, 8)                      # ir_version
        + lfield(2, "whitewater")         # producer_name
        + lfield(7, graph)
        + lfield(8, opset)
    )


def main():
    data = build()
    out = sys.stdout
    out.write("// Generated by tools/ortprobe/make_model.py -- do not edit.\n")
    out.write("// One Add node over two 1x4 float tensors. Inputs \"a\", \"b\"; output \"c\".\n")
    out.write("static const unsigned char kProbeModel[] = {\n")
    for i in range(0, len(data), 12):
        row = ", ".join("0x%02x" % b for b in data[i:i + 12])
        out.write("    %s,\n" % row)
    out.write("};\n")
    out.write("static const unsigned long kProbeModelSize = %d;\n" % len(data))


if __name__ == "__main__":
    main()
